// <auto-generated />
using System;
using CafeOrder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeOrder.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CafeOrder.Modals.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FoodCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodRegionId")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodCategoryId");

                    b.HasIndex("FoodRegionId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoodCategoryId = 1,
                            FoodRegionId = 1,
                            ImgUrl = "#",
                            Introduction = "Green tea is a type of tea that is made from Camellia sinensis leaves and buds that have not undergone the same withering.",
                            Name = "Green Tea",
                            Price = 1.5m,
                            Rating = 3
                        },
                        new
                        {
                            Id = 2,
                            FoodCategoryId = 1,
                            FoodRegionId = 1,
                            ImgUrl = "#",
                            Introduction = "Ramune is a Japanese carbonated soft drink. It was introduced in 1884 in Kobe by the British pharmacist Alexander Cameron Sim. ",
                            Name = "Ramune",
                            Price = 1.6m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            FoodCategoryId = 2,
                            FoodRegionId = 1,
                            ImgUrl = "#",
                            Introduction = "Taiyaki is a Japanese fish-shaped cake, commonly sold as street food. The most common filling is red bean paste that is made from sweetened adzuki beans.",
                            Name = "Taiyaki",
                            Price = 1.8m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 4,
                            FoodCategoryId = 2,
                            FoodRegionId = 1,
                            ImgUrl = "#",
                            Introduction = "Dorayaki is a type of Japanese confection. It consists of two small pancake-like patties made from castella wrapped around a filling of sweet azuki bean paste.",
                            Name = "Dorayaki",
                            Price = 1.8m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 5,
                            FoodCategoryId = 2,
                            FoodRegionId = 1,
                            ImgUrl = "#",
                            Introduction = "Dango is a Japanese dumpling made from rice flour mixed with uruchi rice flour and glutinous rice flour.",
                            Name = "Dango",
                            Price = 1.6m,
                            Rating = 3
                        },
                        new
                        {
                            Id = 6,
                            FoodCategoryId = 2,
                            FoodRegionId = 1,
                            ImgUrl = "#",
                            Introduction = "Takoyaki is a ball-shaped Japanese snack made of a wheat flour-based batter and cooked in a special molded pan. ",
                            Name = "Takoyaki",
                            Price = 2.2m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 7,
                            FoodCategoryId = 1,
                            FoodRegionId = 2,
                            ImgUrl = "#",
                            Introduction = "Banana Flavored Milk is a South Korean milk beverage produced by Binggrae in Korea.",
                            Name = "Banana Flavored Milk",
                            Price = 2.2m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 8,
                            FoodCategoryId = 2,
                            FoodRegionId = 2,
                            ImgUrl = "#",
                            Introduction = "Hotteok, sometimes called Hoeddeok, is a type of filled pancake and is a popular street food in South Korea. ",
                            Name = "Hotteok",
                            Price = 1.8m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 9,
                            FoodCategoryId = 2,
                            FoodRegionId = 2,
                            ImgUrl = "#",
                            Introduction = "walnut cookie is a type of cookie originated from Cheonan, South Korea.",
                            Name = "Walnut cookie",
                            Price = 1.6m,
                            Rating = 3
                        },
                        new
                        {
                            Id = 10,
                            FoodCategoryId = 1,
                            FoodRegionId = 3,
                            ImgUrl = "#",
                            Introduction = "The drink is made from a mixture between coffee and tea. It can be served hot or cold.",
                            Name = "Yuenyeung",
                            Price = 2m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 11,
                            FoodCategoryId = 1,
                            FoodRegionId = 3,
                            ImgUrl = "#",
                            Introduction = "Milk tea refers to several forms of beverage found in many cultures, containing some combination of tea and milk.",
                            Name = "Milktea",
                            Price = 2m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 12,
                            FoodCategoryId = 2,
                            FoodRegionId = 3,
                            ImgUrl = "#",
                            Introduction = "These Cantonese egg tarts are classic pastry in Hong Kong, with buttery, crisp and crumbly tart shell, silky smooth custard inside.",
                            Name = "Eggtart",
                            Price = 1.5m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 13,
                            FoodCategoryId = 2,
                            FoodRegionId = 3,
                            ImgUrl = "#",
                            Introduction = "An egg waffle is a spherical egg-based waffle popular in Hong Kong, consisting of an eggy leavened batter cooked between two plates of semi-spherical cells.",
                            Name = "Egg Waffles ",
                            Price = 1.8m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 14,
                            FoodCategoryId = 2,
                            FoodRegionId = 3,
                            ImgUrl = "#",
                            Introduction = "Peanut butter, butter, sugar and condensed milk are put together in the 2 waffles.",
                            Name = "Baked waffles",
                            Price = 1.8m,
                            Rating = 3
                        });
                });

            modelBuilder.Entity("CafeOrder.Modals.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drink"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Snack"
                        });
                });

            modelBuilder.Entity("CafeOrder.Modals.FoodRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodRegions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hong Kong"
                        });
                });

            modelBuilder.Entity("CafeOrder.Modals.Food", b =>
                {
                    b.HasOne("CafeOrder.Modals.FoodCategory", "FoodCategory")
                        .WithMany()
                        .HasForeignKey("FoodCategoryId");

                    b.HasOne("CafeOrder.Modals.FoodRegion", "FoodRegion")
                        .WithMany()
                        .HasForeignKey("FoodRegionId");

                    b.Navigation("FoodCategory");

                    b.Navigation("FoodRegion");
                });
#pragma warning restore 612, 618
        }
    }
}
